apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: 
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:sqlserver://db-mssql
          - name: SPRING_DATASOURCE_USERNAME
            value: sa
          - name: SPRING_DATASOURCE_PASSWORD
            value: January2018
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq           
          - name: SPRING_RABBITMQ_PORT
            value: "5672"   
---
apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  type: NodePort
  selector:
    app: task
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32244

